services:
  server:
    image: server-image
    build: ./Server
    ports:
      - "5000:5000"
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./Server:/app
    working_dir: /app
    # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py
    command: python main.py
    ulimits:
      nofile:
        soft: 65535
        hard: 524288
    environment:
      - SUBSCRIBED_POWER=${SUBSCRIBED_POWER:-287000}

  client:
    image: client-image
    build: ./Client
    depends_on:
      - server
    volumes:
      - ./Client:/app
      - ./Data:/data
      - ./temp:/shared
    working_dir: /app
    entrypoint: ["./entrypoint.sh"]
    environment:
      - JOB_CHOICES=${JOB_CHOICES:-xsbench minife comd}
      - DELAY_START=${DELAY_START:-15}
      - DELAY_STEP=${DELAY_STEP:-2}
      - HPC_MANAGER_HOST=${HPC_MANAGER_HOST:-192.168.2.122}
      - HPC_MANAGER_PORT=${HPC_MANAGER_PORT:-8000}
      - HPC_MANAGER_FLASK_SERVER_PORT=${HPC_MANAGER_FLASK_SERVER_PORT:-5000}
      - BID_CACHE_Q_MIN=${BID_CACHE_Q_MIN:-0.1}
      - BID_CACHE_Q_MAX=${BID_CACHE_Q_MAX:-5.0}
    

volumes: {}
